### ISSUE TITLE
create_experiment() fails on windows 10

### ISSUE THREAD

**Issue by valko073** [neptune-ml/neptune-client#151]
Hi there, 

I enjoy neptune very much and on my macbook everything works fine. But when I run the same code on my Windows 10 machine, I get an error when calling create_experiment().

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\neptune\__init__.py", line 177, in create_experiment
    notebook_id=notebook_id
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\neptune\projects.py", line 400, in create_experiment
    click.echo(str(experiment.id))
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\click\utils.py", line 218, in echo
    file = _default_text_stdout()
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\ProgramData\Anaconda3\envs\rl_insurance\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
AttributeError: 'StdOutWithUpload' object has no attribute 'fileno'`

It happens when I run:

`import neptune `
`import cfg`
`neptune.init(api_token=cfg.neptune_token, project_qualified_name=cfg.neptune_project_name) `
`neptune.create_experiment()`

I run it in conda environments both times.

**Comment by pitercl** [comment]
Hi @valko073!

Thanks for letting us know. We'll take a look in the next few days.
